AWSTemplateFormatVersion: "2010-09-09"

Description: Moontracer Workshop Notebook

Parameters:
  NotebookInstanceType:
    Type: String
    Default: ml.t3.2xlarge

  NotebookPlatformIdentifier:
    Type: String
    Default: notebook-al2023-v1

  VolumeSizeInGB:
    Type: Number
    Default: 64

Resources:

  WorkshopRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub moontracer-sagemaker-role-${AWS::StackName}

      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - sagemaker.amazonaws.com
            Action:
              - sts:AssumeRole

      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSageMakerFullAccess
        - arn:aws:iam::aws:policy/AdministratorAccess

      Policies:
        - PolicyName: moontracer-inline-policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:*
                  - iam:*
                Resource: "*"

  WorkshopNotebookInstance:
    Type: AWS::SageMaker::NotebookInstance
    Properties:
      InstanceType: !Ref NotebookInstanceType
      PlatformIdentifier: !Ref NotebookPlatformIdentifier
      VolumeSizeInGB: !Ref VolumeSizeInGB
      RoleArn: !GetAtt WorkshopRole.Arn
      AdditionalCodeRepositories:
        - https://github.com/nu01org/moontracer-workshop.git

Outputs:
  NotebookUrl:
    Description: Open notebook
    Value: !Sub
      - https://${NotebookName}.notebook.${AWS::Region}.sagemaker.aws/lab/tree/moontracer-workshop/index.ipynb
      - NotebookName: !GetAtt WorkshopNotebookInstance.NotebookInstanceName
